# Workflow: Code Implementation with Parallel Review
#
# Flow: plan → implement → review (parallel) → finalize → end
#       └──────────────────────────┘ (loop on REJECTED)

name: code-implementation

steps:
  plan:
    agent: general-purpose
    prompt: |
      Analyze the task and create an implementation plan.

      Consider:
      - Architecture and design decisions
      - Files that need to be created or modified
      - Potential risks and edge cases
      - Testing strategy

      End with <!-- DECISION: PLANNED --> or <!-- DECISION: BLOCKED -->
    next:
      - if: PLANNED
        goto: implement
      - if: BLOCKED
        goto: plan
      - goto: plan

  implement:
    agent: general-purpose
    prompt: |
      Implement the task according to the plan in .jdi/reports/{task_id}/plan.md.

      Requirements:
      - Follow project coding standards
      - Write tests for your changes
      - Handle edge cases identified in the plan

      End with <!-- DECISION: DONE --> or <!-- DECISION: ERROR -->
    next:
      - if: DONE
        goto: review
      - if: ERROR
        goto: implement
      - goto: implement

  review:
    parallel:
      - agent: general-purpose
        prompt: |
          Review the implementation in .jdi/reports/{task_id}/implement.md for:
          - Code quality and readability
          - Test coverage and correctness
          - Performance considerations
          - Error handling

          Reference the plan in .jdi/reports/{task_id}/plan.md for context.

          End with <!-- DECISION: APPROVED --> or <!-- DECISION: REJECTED -->
      - agent: general-purpose
        prompt: |
          Review the implementation in .jdi/reports/{task_id}/implement.md for:
          - Security vulnerabilities (OWASP Top 10)
          - Input validation
          - Authentication/authorization issues
          - Data exposure risks

          End with <!-- DECISION: APPROVED --> or <!-- DECISION: REJECTED -->
    check: all
    next:
      - if: APPROVED
        goto: finalize
      - if: REJECTED
        goto: implement
      - goto: implement

  finalize:
    agent: general-purpose
    prompt: |
      Finalize the implementation:
      - Remove any TODO comments
      - Ensure documentation is complete
      - Verify all tests pass
      - Clean up debug code

      Reference:
      - .jdi/reports/{task_id}/plan.md for original requirements
      - .jdi/reports/{task_id}/implement.md for what was built
      - .jdi/reports/{task_id}/review.md for review feedback
    next:
      - goto: end
